import { watch } from "fs";
import { copyFile } from "fs/promises";
import { builtinModules } from "module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProduction = process.argv.includes("--production");
const isWatch = process.argv.includes("--watch");

const external = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtinModules,
];

async function build() {
	const result = await Bun.build({
		entrypoints: ["src/main.ts"],
		outdir: ".",
		naming: "main.js",
		target: "browser",
		format: "cjs",
		sourcemap: isProduction ? "none" : "inline",
		minify: isProduction,
		external,
		banner,
	});

	if (!result.success) {
		console.error("Build failed:");
		for (const log of result.logs) {
			console.error(log);
		}
		return false;
	}

	console.log("Build succeeded");
	return true;
}

async function copyToPluginDir() {
	const files = ["main.js", "manifest.json", "versions.json", "styles.css"];
	for (const file of files) {
		try {
			await copyFile(file, `plugin-dir/${file}`);
		} catch {
			// Ignore if file doesn't exist
		}
	}
	console.log("Copied files to plugin-dir");
}

async function main() {
	const success = await build();

	if (!success && isProduction) {
		process.exit(1);
	}

	if (!isProduction) {
		await copyToPluginDir();
	}

	if (isWatch) {
		console.log("Watching for changes...");

		watch("src", { recursive: true }, async (event, filename) => {
			if (filename?.endsWith(".ts")) {
				console.log(`\nFile changed: ${filename}`);
				await build();
				await copyToPluginDir();
			}
		});

		// Also watch styles.css and copy it when changed
		watch(".", async (event, filename) => {
			if (filename === "styles.css" || filename === "manifest.json" || filename === "versions.json") {
				console.log(`\nFile changed: ${filename}`);
				await copyToPluginDir();
			}
		});
	}
}

main();
